#!/usr/bin/python3
def raise_exception():
    a = 10
    b = "Sum"
    result = a + b
    print("{}".format(result))
